<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:tns="http://conversor.temperatura.com" 
    targetNamespace="http://conversor.temperatura.com">
    <wsdl:types>
        <xs:schema targetNamespace="http://conversor.temperatura.com" elementFormDefault="qualified">
            <xs:include schemaLocation="temperatura.xsd"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="ConvertirMessageRequest">
        <wsdl:part name="parameter" element="tns:request"/>
    </wsdl:message>
    <wsdl:message name="ConvertirMessageResponse">
        <wsdl:part name="parameter" element="tns:response"/>
    </wsdl:message>
    <wsdl:portType name="ConvertirPortType">
        <wsdl:operation name="ConvertirOperation">
            <wsdl:input message="tns:ConvertirMessageRequest"/>
            <wsdl:output message="tns:ConvertirMessageResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ConvertirBinding" type="tns:ConvertirPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="ConvertirOperation">
            <soap:operation soapAction="http://conversor.temperatura.com/ConvertirOperation"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ConvertirService">
        <wsdl:port name="ConvertirPort" binding="tns:ConvertirBinding">
            <soap:address location="http://localhost:8080/ConvertirService"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>